# Generated by Django 4.1.7 on 2024-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_colors_idcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='CodigoDepartamento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='CodigoFamilia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='CodigoProyecto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='CodigoSeccion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='CodigoSubfamilia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Temporada',
            field=models.CharField(max_length=20),
        ),
    ]
