# Generated by Django 4.1.7 on 2024-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_articles_codigodepartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='CodigoDepartamento',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='articles',
            name='CodigoFamilia',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='articles',
            name='CodigoProyecto',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='articles',
            name='CodigoSeccion',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='articles',
            name='CodigoSubfamilia',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Temporada',
            field=models.CharField(max_length=10),
        ),
    ]
