# Generated by Django 4.1.7 on 2024-02-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_articles_codigodepartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='CodigoDepartamento',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Temporada',
            field=models.CharField(max_length=50),
        ),
    ]
