# Generated by Django 4.1.7 on 2024-02-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_ancho_coleccion_design_eje_object_option_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Options',
        ),
        migrations.RemoveField(
            model_name='render',
            name='objeto',
        ),
        migrations.RemoveField(
            model_name='render',
            name='preguntas',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Render',
        ),
    ]
