# Generated by Django 4.1.7 on 2024-02-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_remove_question_options_remove_render_objeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
