# Generated by Django 4.1.7 on 2024-02-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_articles_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='default_name_options',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='coleccion'),
        ),
    ]
