# Generated by Django 4.1.7 on 2024-02-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_coleccion_default_name_options_coleccion_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='img',
            field=models.ImageField(default='default.png', upload_to='coleccion'),
        ),
    ]
