# Generated by Django 4.1.7 on 2024-02-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_coleccion_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='default_ancho',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='server.ancho'),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='default_design',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='server.design'),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='default_eje',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='server.eje'),
        ),
        migrations.CreateModel(
            name='ConfigurationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
                ('ancho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ancho')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.coleccion')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.design')),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.eje')),
            ],
        ),
    ]
