# Generated by Django 4.1.7 on 2024-02-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_remove_configurationobject_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignColeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.png', upload_to='coleccion')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.coleccion')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.design')),
            ],
        ),
    ]
