# Generated by Django 4.1.7 on 2024-02-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_designcoleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancho',
            name='ejes',
            field=models.ManyToManyField(to='server.eje'),
        ),
        migrations.AddField(
            model_name='eje',
            name='image',
            field=models.ImageField(default='default.png', upload_to='eje'),
        ),
    ]
