# Generated by Django 4.1.7 on 2024-02-21 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_ancho_ejes_eje_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ancho',
            name='ejes',
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='default_ancho',
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='default_design',
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='default_eje',
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='default_name_options',
        ),
        migrations.AddField(
            model_name='articles',
            name='design_coleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.designcoleccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designcoleccion',
            name='img',
            field=models.ImageField(default='default.png', upload_to='design_coleccion'),
        ),
    ]
