# Generated by Django 4.1.7 on 2024-03-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_alter_valor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationobject',
            name='ancho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ancho'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='coleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.coleccion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.design'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='eje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.eje'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj1', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj10', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj11', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj12', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion13',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj13', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion14',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj14', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj2', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj3', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj4', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj5', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj6', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj7', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj8', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='opcion9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj9', to='server.opcion'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value1', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value10', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value11', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value12', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor13',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value13', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor14',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value14', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value2', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value3', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value4', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value5', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value6', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value7', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value8', to='server.valor'),
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='valor9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_value9', to='server.valor'),
        ),
    ]
