# Generated by Django 4.1.7 on 2024-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_alter_configurationobject_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eje',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
