# Generated by Django 4.1.7 on 2024-03-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_configurationobject_current_linea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineaconfigurador',
            name='articles',
        ),
        migrations.AddField(
            model_name='lineaconfigurador',
            name='coleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.coleccion'),
            preserve_default=False,
        ),
    ]
